# Generated by Django 3.1.5 on 2021-01-13 15:27

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.jpg', upload_to=myblog.models.user_directory_path),
        ),
    ]
